version: '3.5'

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "delivery"
      POSTGRES_USER: "ruby"
      POSTGRES_PASSWORD: "ruby"

  test-db:
    image: postgres:16
    ports:
      - "5433:5432"
    # https://stackoverflow.com/questions/9407442/optimise-postgresql-for-fast-testing
    command: postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=off -c shared_buffers=512MB -c work-mem=32MB -c autovacuum_max_workers=1 -c autovacuum_naptime=20min
    environment:
      POSTGRES_DB: "delivery_test"
      POSTGRES_USER: "ruby"
      POSTGRES_PASSWORD: "ruby"


  redis:
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  app:
    platform: linux/x86_64
    build: .
    command: ./docker-entrypoint.sh
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./src:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=delivery
      - DB_USER=ruby
      - DB_PASSWORD=ruby
    env_file:
      - src/.env


  celery-beat:
    platform: linux/x86_64
    build: .
    command: celery -A delivery.api.adapters.background_tasks.tasks.app beat -l info
    restart: always
    volumes:
      - ./src:/app
    environment:
      - LOG_LEVEL=DEBUG
    env_file:
      - ./src/.env

  celery-worker:
    platform: linux/x86_64
    build: .
    command: celery -A delivery.api.adapters.background_tasks.tasks.app worker -l info
    restart: always
    volumes:
      - ./src:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=delivery
      - DB_USER=ruby
      - DB_PASSWORD=ruby
      - LOG_LEVEL=DEBUG
    env_file:
      - ./src/.env

volumes:
  db_data:
