version: '3.5'

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "delivery"
      POSTGRES_USER: "ruby"
      POSTGRES_PASSWORD: "ruby"

  test-db:
    image: postgres:16
    ports:
      - "5433:5432"
    # https://stackoverflow.com/questions/9407442/optimise-postgresql-for-fast-testing
    command: postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=off -c shared_buffers=512MB -c work-mem=32MB -c autovacuum_max_workers=1 -c autovacuum_naptime=20min
    environment:
      POSTGRES_DB: "delivery_test"
      POSTGRES_USER: "ruby"
      POSTGRES_PASSWORD: "ruby"

volumes:
  db_data:
