version: '3'

tasks:
  lint:
    cmds:
      - isort src/delivery
      - autoflake --in-place -r src/delivery
      - black src/delivery
      - ruff check src/delivery --fix
      - mypy --config-file=src/pyproject.toml src/delivery
