"""Add courier_id nullable in Order

Revision ID: 436c322996ac
Revises: 6ec21a12d722
Create Date: 2024-07-04 22:55:09.404104

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "436c322996ac"
down_revision: Union[str, None] = "6ec21a12d722"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("orders", "courier_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("orders", "courier_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
