"""Init

Revision ID: 6ec21a12d722
Revises: 
Create Date: 2024-07-04 09:00:27.386231

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6ec21a12d722"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("speed", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transports_id"), "transports", ["id"], unique=False)
    op.create_table(
        "couriers",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("location_x", sa.SmallInteger(), nullable=False),
        sa.Column("location_y", sa.SmallInteger(), nullable=False),
        sa.Column("transport_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["transport_id"],
            ["transports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_couriers_id"), "couriers", ["id"], unique=False)
    op.create_index(op.f("ix_couriers_name"), "couriers", ["name"], unique=False)
    op.create_index(op.f("ix_couriers_transport_id"), "couriers", ["transport_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("location_x", sa.SmallInteger(), nullable=False),
        sa.Column("location_y", sa.SmallInteger(), nullable=False),
        sa.Column("courier_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["courier_id"],
            ["couriers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_courier_id"), "orders", ["courier_id"], unique=False)
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_courier_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_couriers_transport_id"), table_name="couriers")
    op.drop_index(op.f("ix_couriers_name"), table_name="couriers")
    op.drop_index(op.f("ix_couriers_id"), table_name="couriers")
    op.drop_table("couriers")
    op.drop_index(op.f("ix_transports_id"), table_name="transports")
    op.drop_table("transports")
    # ### end Alembic commands ###
